language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
matrix:
    allow_failures:
        - python: "2.6"
        - python: "3.3"
        - python: "3.4"
        - python: "pypy"
    fast_finish: true
install:
    - pip install -r requirements-dev.txt
script:
    - make flake8
